In [3]:
import pandas as pd
import anndata as ad
import numpy as np
import gseapy

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3098, in run_cell
    result = self._run_cell(
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3153, in _run_cell
    result = runner(coro)
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3362, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3607, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3667, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/qb/t7qv2b9n33n2xzbjvg_dk_4c0000gn/T/ipykernel_22603/3499463707.py", line 2, in <module>
    import anndata as ad
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/anndata/__init__.py", line 29, in <module>
    from .io import read_h5ad, read_zarr
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/anndata/io.py", line 7, in <module>
    from ._io.h5ad import read_h5ad, write_h5ad
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/anndata/_io/h5ad.py", line 25, in <module>
    from ..experimental import read_dispatched
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/anndata/experimental/__init__.py", line 12, in <module>
    from .pytorch import AnnLoader
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/anndata/experimental/pytorch/__init__.py", line 3, in <module>
    from ._annloader import AnnLoader
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/anndata/experimental/pytorch/_annloader.py", line 19, in <module>
    import torch
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/kpax/Documents/aep/study/MSC/lab/ppmi-wip/ppmi-env/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

In [11]:
ppmi_ad = ad.read_h5ad("/Users/kpax/Documents/aep/study/MSC/lab/PPMI_Project_133_RNASeq/ppmi_adata.h5ad")

In [12]:
consolidated_gsea_across_visits = "/Users/kpax/Documents/aep/study/MSC/lab/PPMI_Project_133_RNASeq/gsea/ml/enr_ml_cons/enr_results_sorted_common_terms_LR2_Male_50-70.csv"

In [13]:
mask = ((ppmi_ad.obs['Age_Group'] == '50-70') &
        (ppmi_ad.obs['Gender'] == 'Male') &
        (ppmi_ad.obs['Diagnosis'].isin(['PD', 'Control'])))
ppmi_ad = ppmi_ad[mask]

In [14]:
symbol_ensembl_mapping = ppmi_ad.varm['symbol_ensembl_mapping']

In [25]:
gsea_df = pd.read_csv(consolidated_gsea_across_visits, index_col=0)

In [26]:
gsea_df = gsea_df.drop_duplicates(subset='Term')

In [22]:
gsea_df = gsea_df[gsea_df['P-value'] <= 0.05]

In [27]:
gsea_df.shape

(44, 11)

In [30]:
gsea_df.sort_values(by='P-value', ascending=True)

,Unnamed: 0,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes
200,292,ENCODE_TF_ChIP-seq_2015,NR3C1 A549 hg19,1/1855,0.940681,0.999991,0,0,0.348994,2.134132e-02,MIR583
193,129,ChEA_2016,OCT1 27270436 Chip-Seq PROSTATE Human,1/2000,0.953003,0.997123,0,0,0.321089,1.545625e-02,MIR583
194,123,ChEA_2016,LMO2 26923725 Chip-Seq HEMOGENIC-ENDOTHELIUM M...,1/2000,0.953003,0.997123,0,0,0.321089,1.545625e-02,GPX3
196,63,ChEA_2013,SOX2-20726797-SW620-HUMAN,1/2564,0.981343,0.997123,0,0,0.242573,4.568380e-03,GPX3
192,90,ChEA_2015,SOX2 20726797 ChIP-Seq SW620 Human,1/2564,0.981343,0.997123,0,0,0.242573,4.568380e-03,GPX3
199,315,ENCODE_TF_ChIP-seq_2015,MAX HepG2 hg19,1/3158,0.993176,0.999991,0,0,0.190212,1.302436e-03,GPX3
201,321,ENCODE_TF_ChIP-seq_2015,POLR2A endothelial cell of umbilical vein hg19,1/4459,0.999336,0.999991,0,0,0.124279,8.254790e-05,GPX3
147,998,TF-LOF_Expression_from_GEO,pcgf2 17452456 medulloblastoma lof human gpl57...,3/7511,0.999912,0.999948,0,0,0.177825,1.566861e-05,TSPAN13;TUBBP5;FKBP1B
148,999,TF-LOF_Expression_from_GEO,tardbp 19910924 hek293e lof human gpl570 gds37...,1/5400,0.999940,0.999948,0,0,0.089955,5.419002e-06,TSPAN13
149,1000,TF-LOF_Expression_from_GEO,rnf2 20805357 u2os osteosarcoma lof human gpl5...,1/5469,0.999948,0.999948,0,0,0.088399,4.631827e-06,PLSCR4
202,325,ENCODE_TF_ChIP-seq_2015,POLR2A HepG2 hg19,1/6264,0.999979,0.999991,0,0,0.078169,1.656195e-06,GPX3
133,2814,ENCODE_TF_ChIP-seq_2014,POL2 H1,13/9900,0.999994,0.999996,0,0,0.069702,3.939846e-07,FAM27B;MIR4492;RAB3A;SPAG4;CDC42BPA;CTU2;JPH2;...
128,2817,ENCODE_TF_ChIP-seq_2014,POL2 MCF7,17/9679,0.999994,0.999996,0,0,0.097473,5.508055e-07,MIR4492;RAB3A;MIR374C;MIR3619;CDC42BPA;SPTB;CT...
129,2818,ENCODE_TF_ChIP-seq_2014,COREST K562,14/9622,0.999994,0.999996,0,0,0.079844,4.511421e-07,KCNH3;MIR4492;RAB3A;MIR3619;CDC42BPA;SPTB;NCR1...
135,2819,ENCODE_TF_ChIP-seq_2014,GR HEPG2,11/9589,0.999994,0.999996,0,0,0.062114,3.509408e-07,CTU2;MIR1245B;HMGN5;RAB3A;NFIB;DOLPP1;POC1A;ME...
136,2821,ENCODE_TF_ChIP-seq_2014,POL2 HEPG2,14/10572,0.999994,0.999996,0,0,0.065887,3.720867e-07,MIR4492;RAB3A;HERC2P3;SPAG4;MIR499B;CDC42BPA;C...
130,2823,ENCODE_TF_ChIP-seq_2014,POL2 A549,15/9404,0.999994,0.999996,0,0,0.089907,5.076907e-07,FAM27B;KCNH3;MIR4492;HERC2P3;SPAG4;MIR3619;CDC...
131,2824,ENCODE_TF_ChIP-seq_2014,GR H1,14/10650,0.999994,0.999996,0,0,0.064852,3.661320e-07,KCNH3;RAB3A;SPAG4;CDC42BPA;SPTB;CTU2;HMGN5;SLC...
132,2825,ENCODE_TF_ChIP-seq_2014,POL2 HUVEC,16/9305,0.999994,0.999996,0,0,0.098396,5.554184e-07,FAM27B;MIR4492;RAB3A;HERC2P3;MIR499B;MIR3619;C...
137,2828,ENCODE_TF_ChIP-seq_2014,CMYC MCF7,7/9143,0.999994,0.999996,0,0,0.042336,2.387999e-07,MIR4492;RAB3A;TFF3;POC1A;MEGF8;CDC42BPA;SPTB
138,2829,ENCODE_TF_ChIP-seq_2014,STAT3 MCF10A,15/9132,0.999994,0.999996,0,0,0.095008,5.358800e-07,RAB3A;MIR4679-1;SPAG4;MIR31;CTU2;JPH2;CLEC2A;H...
139,2830,ENCODE_TF_ChIP-seq_2014,FOS MCF10A,15/8868,0.999994,0.999996,0,0,0.100259,5.646429e-07,RAB3A;MIR374C;SPAG4;CTU2;JPH2;CLEC2A;HMGN5;DOL...
134,2831,ENCODE_TF_ChIP-seq_2014,TBLR1 K562,11/8796,0.999994,0.999996,0,0,0.072975,4.107906e-07,NCR1;CTU2;MIR4492;RAB3A;DOLPP1;POC1A;MEGF8;CD6...
112,2838,ENCODE_TF_ChIP-seq_2014,POL2 HELA-S3,15/8479,0.999994,0.999996,0,0,0.108593,6.097435e-07,FAM27B;MIR4492;RAB3A;MIR499B;MIR31;MIR3619;CDC...
110,2839,ENCODE_TF_ChIP-seq_2014,POL24H8 SK-N-SH,12/8462,0.999994,0.999996,0,0,0.085736,4.813235e-07,CTU2;FAM27B;MIR4492;MIR1245B;HMGN5;RAB3A;HERC2...
111,2840,ENCODE_TF_ChIP-seq_2014,E2F4 MCF10A,7/8272,0.999994,0.999996,0,0,0.050619,2.836583e-07,CTU2;MIR4492;HMGN5;RAB3A;DOLPP1;CDC42BPA;SPTB
121,2844,ENCODE_TF_ChIP-seq_2014,POL2 MCF10A,12/7962,0.999994,0.999996,0,0,0.095143,5.313213e-07,CTU2;JPH2;HMGN5;RAB3A;ADAM12;TFF3;POC1A;CD300L...
120,2858,ENCODE_TF_ChIP-seq_2014,POL2 GM12878,6/7460,0.999994,0.999996,0,0,0.051226,2.840732e-07,NCR1;CTU2;HMGN5;POC1A;MEGF8;CDC42BPA
113,2861,ENCODE_TF_ChIP-seq_2014,POL2 PROGFIB,14/7413,0.999994,0.999996,0,0,0.126153,6.990710e-07,MIR4492;RAB3A;TAS2R43;SPAG4;MIR3619;CDC42BPA;C...
108,2862,ENCODE_TF_ChIP-seq_2014,POL2 ECC1,9/7410,0.999994,0.999996,0,0,0.078942,4.374294e-07,CTU2;MIR4492;HMGN5;DOLPP1;POC1A;MEGF8;CD68;CDC...
127,2872,ENCODE_TF_ChIP-seq_2014,POL2 GM12891,6/7125,0.999994,0.999996,0,0,0.055091,3.037923e-07,HMGN5;RAB3A;HERC2P3;POC1A;MEGF8;MIR3153
109,2877,ENCODE_TF_ChIP-seq_2014,WHIP GM12878,6/7039,0.999994,0.999996,0,0,0.056143,3.091041e-07,MIR1245B;RAB3A;POC1A;MEGF8;A4GALT;MIR3153
114,2879,ENCODE_TF_ChIP-seq_2014,POL24H8 PANC1,11/7015,0.999994,0.999996,0,0,0.106331,5.851571e-07,CTU2;FAM27B;HMGN5;HERC2P3;POC1A;MIR499B;MEGF8;...
125,2907,ENCODE_TF_ChIP-seq_2014,POL24H8 K562,10/6328,0.999995,0.999996,0,0,0.112311,6.088910e-07,NCR1;CTU2;HMGN5;RAB3A;POC1A;MEGF8;CD68;CDC42BP...
126,2909,ENCODE_TF_ChIP-seq_2014,COREST GM12878,5/6250,0.999995,0.999996,0,0,0.055655,3.011401e-07,CTU2;MIR1245B;RAB3A;POC1A;MEGF8
122,2919,ENCODE_TF_ChIP-seq_2014,ELK1 HELA-S3,5/6070,0.999995,0.999996,0,0,0.058068,3.127049e-07,RAB3A;DOLPP1;POC1A;MEGF8;SPTB
123,2920,ENCODE_TF_ChIP-seq_2014,CHD2 HEPG2,6/6053,0.999995,0.999996,0,0,0.070341,3.786275e-07,MIR4492;HMGN5;RAB3A;TFF3;MEGF8;CDC42BPA
124,2921,ENCODE_TF_ChIP-seq_2014,RAD21 H1,10/6042,0.999995,0.999996,0,0,0.120131,6.464334e-07,CTU2;KCNH3;MIR4492;MIR1245B;MIR4290;ADAM12;MEG...
140,2925,ENCODE_TF_ChIP-seq_2014,SP4 H1,5/5998,0.999995,0.999996,0,0,0.059073,3.174956e-07,RAB3A;DOLPP1;MEGF8;CD68;CDC42BPA
115,2941,ENCODE_TF_ChIP-seq_2014,YY1 HEPG2,6/5756,0.999995,0.999996,0,0,0.075571,4.033200e-07,CTU2;MIR4492;RAB3A;DOLPP1;CD68;CDC42BPA
116,2966,ENCODE_TF_ChIP-seq_2014,MAX NB4,5/5349,0.999995,0.999996,0,0,0.069361,3.652871e-07,JPH2;RAB3A;PRTN3;MEGF8;CD68
118,3034,ENCODE_TF_ChIP-seq_2014,SMC3 K562,4/4130,0.999995,0.999996,0,0,0.077527,3.870014e-07,CTU2;MEGF8;CDC42BPA;SPTB
119,3073,ENCODE_TF_ChIP-seq_2014,SMC3 HEPG2,6/3515,0.999995,0.999996,0,0,0.143587,6.902342e-07,MIR1245B;RAB3A;POC1A;MEGF8;CD68;SPTB
117,3077,ENCODE_TF_ChIP-seq_2014,PU1 GM12878,6/3481,0.999995,0.999996,0,0,0.145294,6.967963e-07,CTU2;HERC2P3;PRTN3;CD300LD;CD68;FCGR2B

In [34]:
feature_imp_male_50_70_bl = pd.read_csv("/Users/kpax/Documents/aep/study/MSC/lab/PPMI_Project_133_RNASeq/classification/LR2/feature_importance_data_Male_50-70_BL.csv", index_col=1)

In [36]:
feature_imp_male_50_70_bl

                    Unnamed: 0  importance  abs_importance      gene_symbol
feature
ENSG00000271725.1         1372   -0.922282        0.922282  ENSG00000271725
ENSG00000267379.1         1613    0.874734        0.874734  ENSG00000267379
ENSG00000222533.1          589   -0.808817        0.808817        RNU6-705P
ENSG00000260075.1         1507   -0.801751        0.801751         LRRC37A2
ENSG00000248925.1          516    0.760267        0.760267         PDCD6-DT
...                        ...         ...             ...              ...
ENSG00000129675.15        1848    0.000000        0.000000          ARHGEF6
ENSG00000252719.1         1849    0.000000        0.000000  ENSG00000252719
ENSG00000225758.1         1850    0.000000        0.000000         RPS17P17
ENSG00000037637.10          16    0.000000        0.000000           FBXO42
ENSG00000065526.10          14    0.000000        0.000000             SPEN

[1885 rows x 4 columns]

In [37]:
deg_male_50_70_bl = pd.read_csv("/Users/kpax/Documents/aep/study/MSC/lab/PPMI_Project_133_RNASeq/dge_stratified/DEGs_stratified_Male_BL_50-70.csv", index_col=0)

In [42]:
deg_feature_imp_intersection = deg_male_50_70_bl[deg_male_50_70_bl.index.isin(feature_imp_male_50_70_bl.index)]

In [45]:
deg_feature_imp_intersection = deg_feature_imp_intersection.sort_values(by=['log2FoldChange', 'pvalue'], ascending=[False, True])

In [46]:
deg_feature_imp_intersection

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Gene,,,,,,
ENSG00000277613.1,0.544556,0.716081,0.325670,2.198795,2.789247e-02,NaN
ENSG00000281741.2,27.991287,0.654404,0.147003,4.451634,8.521949e-06,0.016843
ENSG00000201684.1,1.029783,0.606689,0.245726,2.468968,1.355035e-02,NaN
ENSG00000260304.1,0.652940,0.454450,0.394883,1.150846,2.497956e-01,NaN
ENSG00000212279.2,0.913591,0.451306,0.268336,1.681872,9.259364e-02,NaN
...,...,...,...,...,...,...
ENSG00000225906.1,1.046582,-1.549369,0.595854,-2.600251,9.315551e-03,NaN
ENSG00000237835.1,1.093162,-1.567314,0.523877,-2.991761,2.773731e-03,NaN
ENSG00000250416.2,1.642109,-1.626374,0.521893,-3.116297,1.831374e-03,NaN
ENSG00000268884.1,1.087278,-1.640157,0.625264,-2.623143,8.712259e-03,NaN
ENSG00000241032.3,1.765436,-1.680425,0.336790,-4.989527,6.052718e-07,NaN

In [49]:
deg_feature_imp_intersection = deg_feature_imp_intersection.merge(symbol_ensembl_mapping, left_index=True, right_index=True)

In [52]:
deg_feature_imp_intersection = deg_feature_imp_intersection.sort_values(by="pvalue", ascending=True)

In [53]:
deg_feature_imp_intersection

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,gene_symbol,trunc_eid
ENSG00000241032.3,1.765436,-1.680425,0.336790,-4.989527,6.052718e-07,NaN,RN7SL709P,ENSG00000241032
ENSG00000281741.2,27.991287,0.654404,0.147003,4.451634,8.521949e-06,0.016843,ENSG00000281741,ENSG00000281741
ENSG00000285215.2,86.133282,0.337333,0.079142,4.262386,2.022553e-05,0.024377,ENSG00000285215,ENSG00000285215
ENSG00000264618.2,4.074548,-0.996977,0.257075,-3.878155,1.052519e-04,NaN,RN7SL732P,ENSG00000264618
ENSG00000246560.2,44.548341,0.174201,0.045920,3.793561,1.485021e-04,0.065711,UBE2D3-AS1,ENSG00000246560
...,...,...,...,...,...,...,...,...
ENSG00000117899.10,1077.221993,-0.000233,0.021823,-0.010663,9.914920e-01,0.995086,MESD,ENSG00000117899
ENSG00000196118.11,118.657131,0.000406,0.045453,0.008924,9.928794e-01,0.995888,CFAP119,ENSG00000196118
ENSG00000186162.10,222.233088,0.000063,0.028495,0.002223,9.982265e-01,0.998941,CIDECP1,ENSG00000186162
ENSG00000271590.1,60.171026,0.000086,0.064838,0.001333,9.989365e-01,0.999418,ENSG00000271590,ENSG00000271590
ENSG00000212933.1,4.387138,-0.000199,0.191112,-0.001039,9.991712e-01,0.999576,KRTAP12-4,ENSG00000212933