In [1]:
PATH = "/Users/kpax/Documents/aep/study/MSC/lab/PPMI_Project_133_RNASeq/classification"

In [2]:
classifier_result_dirs = ["LR2", "SVM2", "RF2", "XGBOOST2"]
visits = ["BL", "V02", "V04", "V06", "V08"]

In [3]:
import pandas as pd

dataframes = {classifier_result_dir: {visit: None for visit in visits} for classifier_result_dir in classifier_result_dirs}

for classifier_result_dir in classifier_result_dirs:
    for visit in visits:
        feature_importance_file = f"{PATH}/{classifier_result_dir}/feature_importance_data_Male_50-70_{visit}.csv"
        df = pd.read_csv(feature_importance_file)
        dataframes[classifier_result_dir][visit] = df

In [4]:
dataframes

{'LR2': {'BL':       Unnamed: 0             feature  importance  abs_importance  \
  0           1372   ENSG00000271725.1   -0.922282        0.922282
  1           1613   ENSG00000267379.1    0.874734        0.874734
  2            589   ENSG00000222533.1   -0.808817        0.808817
  3           1507   ENSG00000260075.1   -0.801751        0.801751
  4            516   ENSG00000248925.1    0.760267        0.760267
  ...          ...                 ...         ...             ...
  1880        1848  ENSG00000129675.15    0.000000        0.000000
  1881        1849   ENSG00000252719.1    0.000000        0.000000
  1882        1850   ENSG00000225758.1    0.000000        0.000000
  1883          16  ENSG00000037637.10    0.000000        0.000000
  1884          14  ENSG00000065526.10    0.000000        0.000000

            gene_symbol
  0     ENSG00000271725
  1     ENSG00000267379
  2           RNU6-705P
  3            LRRC37A2
  4            PDCD6-DT
  ...               ...
  1880          ARHGEF6
  1881  ENSG00000252719
  1882         RPS17P17
  1883           FBXO42
  1884             SPEN

  [1885 rows x 5 columns],
  'V02':       Unnamed: 0            feature  importance  abs_importance  \
  0             77  ENSG00000251720.1   -0.214967        0.214967
  1            974  ENSG00000252523.1   -0.189953        0.189953
  2            714  ENSG00000250806.2    0.186853        0.186853
  3           1693  ENSG00000272158.1   -0.172639        0.172639
  4           1241  ENSG00000282996.1    0.159007        0.159007
  ...          ...                ...         ...             ...
  2407          39  ENSG00000229607.1    0.000000        0.000000
  2408          40  ENSG00000203620.2    0.000000        0.000000
  2409          41  ENSG00000222046.2    0.000000        0.000000
  2410          42  ENSG00000236065.2    0.000000        0.000000
  2411          43  ENSG00000234512.1    0.000000        0.000000

            gene_symbol
  0           RNU7-123P
  1           RNU6-267P
  2     ENSG00000250806
  3     ENSG00000272158
  4             MPP7-DT
  ...               ...
  2407  ENSG00000229607
  2408  ENSG00000203620
  2409           DCDC2B
  2410  ENSG00000236065
  2411           TLR12P

  [2412 rows x 5 columns],
  'V04':       Unnamed: 0             feature  importance  abs_importance  \
  0            206   ENSG00000233594.2   -0.876211        0.876211
  1            183   ENSG00000224521.1   -0.816300        0.816300
  2            811   ENSG00000253603.1    0.743783        0.743783
  3           1125   ENSG00000254478.1   -0.730097        0.730097
  4            441   ENSG00000250612.2   -0.728385        0.728385
  ...          ...                 ...         ...             ...
  2008          33  ENSG00000186501.14    0.000000        0.000000
  2009          34   ENSG00000225886.3    0.000000        0.000000
  2010          35   ENSG00000253304.1    0.000000        0.000000
  2011          36   ENSG00000236335.1    0.000000        0.000000
  2012          14  ENSG00000009724.16    0.000000        0.000000

            gene_symbol
  0              BTF3P5
  1        LOC124904576
  2              CERNA3
  3             COX7CP3
  4     ENSG00000250612
  ...               ...
  2008          TMEM222
  2009  ENSG00000225886
  2010         TMEM200B
  2011  ENSG00000236335
  2012            MASP2

  [2013 rows x 5 columns],
  'V06':       Unnamed: 0             feature  importance  abs_importance  \
  0            769   ENSG00000240534.1    0.365556        0.365556
  1            760   ENSG00000253393.1   -0.329063        0.329063
  2           1751   ENSG00000226031.5    0.309159        0.309159
  3            543   ENSG00000240518.2    0.259742        0.259742
  4           1728   ENSG00000204072.3   -0.232202        0.232202
  ...          ...                 ...         ...             ...
  1774        1742  ENSG00000185903.10    0.000000        0.000000
  1775        1743   ENSG00000227183.3    0.000000        0.000000
  1776        1744   ENSG00000232068.1    0.000000        0.000000
  1777        1745   ENSG00000232664.2    0.000000        0.000000
  1778           4   ENSG00000276189.1    0.000000        0.000000

            gene_symbol
  0            RPL34P17
  1               RANP9
  2           FGF13-AS1
  3            RPL36P11
  4             ARMCX7P
  ...               ...
  1774          OR11N1P
  1775           HDGFP1
  1776  ENSG00000232068
  1777         LARP1BP3
  1778  ENSG00000276189

  [1779 rows x 5 columns],
  'V08':       Unnamed: 0             feature  importance  abs_importance  \
  0            681  ENSG00000211445.11    0.364944        0.364944
  1            635   ENSG00000240627.1   -0.350438        0.350438
  2           1322   ENSG00000254420.1    0.296562        0.296562
  3           1526   ENSG00000264712.3   -0.292887        0.292887
  4           1862   ENSG00000273524.1    0.236443        0.236443
  ...          ...                 ...         ...             ...
  2204          28   ENSG00000232482.2    0.000000        0.000000
  2205          29   ENSG00000227312.2    0.000000        0.000000
  2206          30   ENSG00000233478.1    0.000000        0.000000
  2207          31   ENSG00000229607.1    0.000000        0.000000
  2208           8   ENSG00000225126.1    0.000000        0.000000

            gene_symbol
  0                GPX3
  1            RPS10P12
  2     ENSG00000254420
  3             MIR4504
  4         Metazoa_SRP
  ...               ...
  2204  ENSG00000232482
  2205          RPL26P8
  2206  ENSG00000233478
  2207  ENSG00000229607
  2208       CAMTA1-AS1

  [2209 rows x 5 columns]},
 'SVM2': {'BL':       Unnamed: 0             feature  importance  coefficient  abs_importance  \
  0           1372   ENSG00000271725.1    0.058422    -0.058422        0.058422
  1            589   ENSG00000222533.1    0.056281    -0.056281        0.056281
  2           1415   ENSG00000260304.1    0.051444     0.051444        0.051444
  3            165   ENSG00000232134.1    0.051327    -0.051327        0.051327
  4           1613   ENSG00000267379.1    0.048957     0.048957        0.048957
  ...          ...                 ...         ...          ...             ...
  1880         370   ENSG00000240895.1    0.000021     0.000021        0.000021
  1881          92   ENSG00000240244.3    0.000013    -0.000013        0.000013
  1882         891   ENSG00000226047.1    0.000013    -0.000013        0.000013
  1883         505  ENSG00000154447.14    0.000004    -0.000004        0.000004
  1884        1558   ENSG00000267247.1    0.000002     0.000002        0.000002

            gene_symbol
  0     ENSG00000271725
  1           RNU6-705P
  2     ENSG00000260304
  3           RPS15AP12
  4     ENSG00000267379
  ...               ...
  1880  ENSG00000240895
  1881         GAPDHP33
  1882  ENSG00000226047
  1883           SH3RF1
  1884  ENSG00000267247

  [1885 rows x 6 columns],
  'V02':       Unnamed: 0             feature  importance  abs_importance  \
  0           1219   ENSG00000197191.4   -0.047368        0.047368
  1           2223   ENSG00000232260.2   -0.042105        0.042105
  2            738   ENSG00000278925.1   -0.036842        0.036842
  3            913   ENSG00000235454.1   -0.036842        0.036842
  4           1241   ENSG00000282996.1   -0.036842        0.036842
  ...          ...                 ...         ...             ...
  2407          58  ENSG00000162365.11    0.000000        0.000000
  2408          59   ENSG00000237337.1    0.000000        0.000000
  2409          44  ENSG00000176256.10    0.000000        0.000000
  2410          45  ENSG00000142698.14    0.000000        0.000000
  2411          61   ENSG00000261664.5    0.000000        0.000000

            gene_symbol
  0              CYSRT1
  1            BTF3L4P1
  2     ENSG00000278925
  3             HAUS6P3
  4             MPP7-DT
  ...               ...
  2407          CYP4A22
  2408       ELAVL4-AS1
  2409            HMGB4
  2410          C1orf94
  2411       TTC39A-AS1

  [2412 rows x 5 columns],
  'V04':       Unnamed: 0             feature  importance  coefficient  abs_importance  \
  0           1867   ENSG00000281383.1    0.056109     0.056109        0.056109
  1            619   ENSG00000270761.1    0.046712    -0.046712        0.046712
  2            508   ENSG00000240376.1    0.046005    -0.046005        0.046005
  3            183   ENSG00000224521.1    0.044745    -0.044745        0.044745
  4            818   ENSG00000254213.2    0.042850    -0.042850        0.042850
  ...          ...                 ...         ...          ...             ...
  2008        1749   ENSG00000205786.8    0.000048    -0.000048        0.000048
  2009        1287   ENSG00000285572.1    0.000041     0.000041        0.000041
  2010         934  ENSG00000136867.10    0.000035     0.000035        0.000035
  2011         414  ENSG00000118564.14    0.000030    -0.000030        0.000030
  2012          58  ENSG00000132854.18    0.000011     0.000011        0.000011

            gene_symbol
  0     ENSG00000281383
  1            CD2AP-DT
  2              RPS8P8
  3        LOC124904576
  4            PRXL2AP2
  ...               ...
  2008        LINC01531
  2009     LOC124903183
  2010          SLC31A2
  2011            FBXL5
  2012            KANK4

  [2013 rows x 6 columns],
  'V06':       Unnamed: 0             feature  importance  abs_importance  \
  0           1751   ENSG00000226031.5    0.036364        0.036364
  1           1541   ENSG00000270402.1    0.031818        0.031818
  2           1723   ENSG00000212623.1    0.027273        0.027273
  3           1691   ENSG00000189060.5    0.027273        0.027273
  4           1340   ENSG00000259553.5    0.022727        0.022727
  ...          ...                 ...         ...             ...
  1774         306   ENSG00000200822.1    0.000000        0.000000
  1775         305  ENSG00000135903.19    0.000000        0.000000
  1776         304   ENSG00000227308.2    0.000000        0.000000
  1777         303  ENSG00000115649.15    0.000000        0.000000
  1778          55  ENSG00000162367.11    0.000000        0.000000

            gene_symbol
  0           FGF13-AS1
  1     ENSG00000270402
  2           RNU6-493P
  3                H1-0
  4     ENSG00000259553
  ...               ...
  1774            Y_RNA
  1775             PAX3
  1776     LOC105373888
  1777           CNPPD1
  1778             TAL1

  [1779 rows x 5 columns],
  'V08':       Unnamed: 0            feature  importance  abs_importance  \
  0            906  ENSG00000272647.3   -0.028571        0.028571
  1             89  ENSG00000227850.1   -0.023810        0.023810
  2           1505  ENSG00000257310.1   -0.023810        0.023810
  3           2202  ENSG00000233774.1   -0.023810        0.023810
  4           1786  ENSG00000225582.1   -0.023810        0.023810
  ...          ...                ...         ...             ...
  2204          44  ENSG00000281825.1    0.000000        0.000000
  2205          45  ENSG00000232467.2    0.000000        0.000000
  2206          46  ENSG00000186160.4    0.000000        0.000000
  2207        2175  ENSG00000227303.1    0.000000        0.000000
  2208        2153  ENSG00000223904.2    0.000000        0.000000

            gene_symbol
  0     ENSG00000272647
  1           SEPTIN2P1
  2     ENSG00000257310
  3             MED14P1
  4     ENSG00000225582
  ...               ...
  2204  ENSG00000281825
  2205          TMA16P2
  2206           CYP4Z1
  2207  ENSG00000227303
  2208         HMGB1P12

  [2209 rows x 5 columns]},
 'RF2': {'BL':       Unnamed: 0            feature  importance  abs_importance  \
  0             94  ENSG00000281741.2    0.060962        0.060962
  1            135  ENSG00000221545.1    0.032815        0.032815
  2            589  ENSG00000222533.1    0.032651        0.032651
  3            364  ENSG00000282527.1    0.021952        0.021952
  4            645  ENSG00000223821.1    0.016132        0.016132
  ...          ...                ...         ...             ...
  1880         235  ENSG00000281904.1    0.000000        0.000000
  1881         237  ENSG00000273634.1    0.000000        0.000000
  1882         119  ENSG00000235919.4    0.000000        0.000000
  1883         185  ENSG00000232793.2    0.000000        0.000000
  1884        1813  ENSG00000228004.1    0.000000        0.000000

            gene_symbol
  0     ENSG00000281741
  1           MIR1255B2
  2           RNU6-705P
  3     ENSG00000282527
  4     ENSG00000223821
  ...               ...
  1880  ENSG00000281904
  1881  ENSG00000273634
  1882        ASH1L-AS1
  1883        DNAJC19P8
  1884           MYCLP2

  [1885 rows x 5 columns],
  'V02':       Unnamed: 0            feature  importance  abs_importance  \
  0           2223  ENSG00000232260.2    0.007047        0.007047
  1           1500  ENSG00000255693.2    0.005882        0.005882
  2            738  ENSG00000278925.1    0.005763        0.005763
  3            517  ENSG00000206600.1    0.005671        0.005671
  4             77  ENSG00000251720.1    0.005390        0.005390
  ...          ...                ...         ...             ...
  2407        2363  ENSG00000225728.2    0.000000        0.000000
  2408        2340  ENSG00000235136.1    0.000000        0.000000
  2409        2343  ENSG00000215162.1    0.000000        0.000000
  2410        2346  ENSG00000231963.1    0.000000        0.000000
  2411        1280  ENSG00000273497.1    0.000000        0.000000

            gene_symbol
  0            BTF3L4P1
  1           LINC02389
  2     ENSG00000278925
  3            RNU6-25P
  4           RNU7-123P
  ...               ...
  2407        TMEM230P1
  2408          PSMA5P1
  2409        LINC00269
  2410     LOC101928380
  2411  ENSG00000273497

  [2412 rows x 5 columns],
  'V04':       Unnamed: 0             feature  importance  abs_importance   gene_symbol
  0           1238   ENSG00000196668.3    0.057299        0.057299     LINC00173
  1           1161   ENSG00000255374.3    0.026401        0.026401       TAS2R43
  2            865   ENSG00000227155.7    0.018241        0.018241  LOC124902108
  3           1218   ENSG00000264978.2    0.016623        0.016623     RN7SL630P
  4             45   ENSG00000200254.1    0.016116        0.016116     RNU6-536P
  ...          ...                 ...         ...             ...           ...
  2008          88   ENSG00000274450.1    0.000000        0.000000  LOC124900456
  2009          19   ENSG00000252151.1    0.000000        0.000000    RNU6-1265P
  2010          30  ENSG00000158062.20    0.000000        0.000000        UBXN11
  2011          32   ENSG00000241188.3    0.000000        0.000000     RN7SL165P
  2012          17   ENSG00000231103.2    0.000000        0.000000     PRAMEF30P

  [2013 rows x 5 columns],
  'V06':       Unnamed: 0            feature  importance  abs_importance  \
  0            660  ENSG00000106537.7    0.025771        0.025771
  1            760  ENSG00000253393.1    0.024028        0.024028
  2            780  ENSG00000254006.5    0.022997        0.022997
  3           1751  ENSG00000226031.5    0.020395        0.020395
  4            769  ENSG00000240534.1    0.018790        0.018790
  ...          ...                ...         ...             ...
  1774          32  ENSG00000270927.1    0.000000        0.000000
  1775        1753  ENSG00000225469.3    0.000000        0.000000
  1776        1754  ENSG00000201594.1    0.000000        0.000000
  1777        1756  ENSG00000228855.1    0.000000        0.000000
  1778         214  ENSG00000108442.2    0.000000        0.000000

            gene_symbol
  0             TSPAN13
  1               RANP9
  2        LOC105375878
  3           FGF13-AS1
  4            RPL34P17
  ...               ...
  1774  ENSG00000270927
  1775        LOC392555
  1776        RNA5SP517
  1777  ENSG00000228855
  1778         TVP23BP2

  [1779 rows x 5 columns],
  'V08':       Unnamed: 0             feature  importance  abs_importance  \
  0           1295   ENSG00000234964.4    0.031666        0.031666
  1            594   ENSG00000250739.1    0.030767        0.030767
  2           1642   ENSG00000278514.1    0.025723        0.025723
  3            681  ENSG00000211445.11    0.019792        0.019792
  4           1432   ENSG00000258249.1    0.018982        0.018982
  ...          ...                 ...         ...             ...
  2204          53   ENSG00000230604.2    0.000000        0.000000
  2205          12   ENSG00000204510.5    0.000000        0.000000
  2206          56   ENSG00000279049.1    0.000000        0.000000
  2207          59   ENSG00000230546.1    0.000000        0.000000
  2208           9   ENSG00000271264.1    0.000000        0.000000

            gene_symbol
  0             FABP5P7
  1           LINC01262
  2     ENSG00000278514
  3                GPX3
  4     ENSG00000258249
  ...               ...
  2204         TSEN15P2
  2205          PRAMEF7
  2206  ENSG00000279049
  2207  ENSG00000230546
  2208           MZT1P1

  [2209 rows x 5 columns]},
 'XGBOOST2': {'BL':       Unnamed: 0             feature  importance  abs_importance
  0           1261   ENSG00000256221.1    0.033189        0.033189
  1           1818   ENSG00000231651.1    0.024756        0.024756
  2            194   ENSG00000206732.1    0.019586        0.019586
  3           1289  ENSG00000100731.15    0.018059        0.018059
  4            927   ENSG00000272914.1    0.016342        0.016342
  ...          ...                 ...         ...             ...
  1880        1848  ENSG00000129675.15    0.000000        0.000000
  1881        1849   ENSG00000252719.1    0.000000        0.000000
  1882        1850   ENSG00000225758.1    0.000000        0.000000
  1883          15   ENSG00000234607.2    0.000000        0.000000
  1884          14  ENSG00000065526.10    0.000000        0.000000

  [1885 rows x 4 columns],
  'V02':       Unnamed: 0             feature  importance  abs_importance
  0            116   ENSG00000282887.2    0.011395        0.011395
  1            120   ENSG00000272715.1    0.011037        0.011037
  2           1300   ENSG00000283095.1    0.010776        0.010776
  3           2245   ENSG00000273362.1    0.010213        0.010213
  4           2240   ENSG00000236384.7    0.009710        0.009710
  ...          ...                 ...         ...             ...
  2407          58  ENSG00000162365.11    0.000000        0.000000
  2408          59   ENSG00000237337.1    0.000000        0.000000
  2409        2316   ENSG00000223731.2    0.000000        0.000000
  2410        2317   ENSG00000169297.7    0.000000        0.000000
  2411        2379   ENSG00000231929.2    0.000000        0.000000

  [2412 rows x 4 columns],
  'V04':       Unnamed: 0             feature  importance  abs_importance
  0           1303   ENSG00000139890.9    0.019987        0.019987
  1           1238   ENSG00000196668.3    0.018934        0.018934
  2             63   ENSG00000237852.1    0.016421        0.016421
  3           1148   ENSG00000256433.2    0.014382        0.014382
  4           1988   ENSG00000202231.1    0.014243        0.014243
  ...          ...                 ...         ...             ...
  2008          20   ENSG00000224459.1    0.000000        0.000000
  2009          19   ENSG00000252151.1    0.000000        0.000000
  2010          17   ENSG00000231103.2    0.000000        0.000000
  2011        1979   ENSG00000270641.1    0.000000        0.000000
  2012          14  ENSG00000009724.16    0.000000        0.000000

  [2013 rows x 4 columns],
  'V06':       Unnamed: 0             feature  importance  abs_importance
  0           1149   ENSG00000229791.1    0.053485        0.053485
  1            309  ENSG00000144468.16    0.046197        0.046197
  2           1320   ENSG00000279719.1    0.027467        0.027467
  3            641   ENSG00000216475.1    0.024431        0.024431

In [5]:
# Find common genes in the 'feature' column across all classifiers for a particular visit
# Create a final dataframe with additional columns for importance values from each classifier

result_dataframes_per_visit = {}

for visit in visits:
    # Find common features across all classifiers for the current visit
    common_features = set.intersection(*[set(dataframes[classifier][visit]['feature']) for classifier in classifier_result_dirs])

    # Create a list to store rows for the resulting dataframe
    result_rows = []
    for feature in common_features:
        row = {'feature': feature}
        # Add importance values for each classifier
        for classifier in classifier_result_dirs:
            df = dataframes[classifier][visit]
            importance_value = df.loc[df['feature'] == feature, 'importance'].values
            row[f"importance_{classifier}"] = importance_value[0] if len(importance_value) > 0 else 0
        result_rows.append(row)

    # Create a dataframe for the visit with the intersected features and importances
    result_dataframes_per_visit[visit] = pd.DataFrame(result_rows)

In [34]:
filtered_df = result_dataframes_per_visit['BL'][(result_dataframes_per_visit['BL'].iloc[:, 1:] > 0).all(axis=1)]
filtered_df

,feature,importance_LR2,importance_SVM2,importance_RF2,importance_XGBOOST2
9,ENSG00000271153.1,0.166335,0.030227,0.000924,0.001482
26,ENSG00000280655.1,0.247769,0.029796,0.000427,0.000964
34,ENSG00000102128.8,0.088874,0.017395,0.000491,0.003159
63,ENSG00000199562.1,0.221114,0.023699,0.001522,0.008138
69,ENSG00000276855.1,0.427339,0.040450,0.000970,0.001158
...,...,...,...,...,...
1793,ENSG00000198574.5,0.176447,0.008810,0.001519,0.005737
1800,ENSG00000177685.16,0.031727,0.013796,0.000675,0.010371
1823,ENSG00000267593.1,0.000331,0.002445,0.000428,0.000183
1848,ENSG00000271538.5,0.216786,0.018578,0.001054,0.002974
1873,ENSG00000253182.1,0.261327,0.030895,0.000528,0.000515

In [28]:
filtered_df = result_dataframes_per_visit['V02'][(result_dataframes_per_visit['V02'].iloc[:, 1:] > 0).all(axis=1)]
filtered_df

,feature,importance_LR2,importance_SVM2,importance_RF2,importance_XGBOOST2
1765,ENSG00000179750.15,0.091419,0.010526,0.003661,0.001979

In [29]:
filtered_df = result_dataframes_per_visit['V04'][(result_dataframes_per_visit['V04'].iloc[:, 1:] > 0).all(axis=1)]
filtered_df

,feature,importance_LR2,importance_SVM2,importance_RF2,importance_XGBOOST2
14,ENSG00000272009.1,0.223499,0.020636,0.001109,0.002176
15,ENSG00000120337.8,0.006602,0.018610,0.000288,0.000325
22,ENSG00000135519.7,0.197807,0.018467,0.001133,0.001132
23,ENSG00000223262.1,0.475017,0.033683,0.000284,0.000988
28,ENSG00000213937.3,0.006155,0.005931,0.000399,0.000550
...,...,...,...,...,...
1920,ENSG00000200875.1,0.387961,0.022680,0.001542,0.004371
1943,ENSG00000259062.2,0.469251,0.030944,0.000981,0.000818
1971,ENSG00000205810.8,0.033621,0.003272,0.000711,0.000326
1991,ENSG00000253603.1,0.743783,0.039148,0.007891,0.003491
2008,ENSG00000225850.3,0.033172,0.014136,0.000509,0.000591

In [30]:
filtered_df = result_dataframes_per_visit['V06'][(result_dataframes_per_visit['V06'].iloc[:, 1:] > 0).all(axis=1)]
filtered_df

,feature,importance_LR2,importance_SVM2,importance_RF2,importance_XGBOOST2
472,ENSG00000254006.5,0.096529,0.013636,0.022997,0.005249
497,ENSG00000226031.5,0.309159,0.018182,0.020395,0.008605
700,ENSG00000270402.1,0.033631,0.031818,0.003963,0.001690
725,ENSG00000268997.1,0.038828,0.004545,0.002547,0.005356
824,ENSG00000240518.2,0.259742,0.018182,0.010604,0.001611
877,ENSG00000272636.3,0.039079,0.004545,0.009836,0.006189
901,ENSG00000267035.1,0.145558,0.004545,0.011078,0.003364
1052,ENSG00000159247.13,0.026927,0.004545,0.001910,0.008152
1237,ENSG00000275215.1,0.178738,0.004545,0.005218,0.001883
1342,ENSG00000154537.4,0.030770,0.036364,0.005900,0.011484
1561,ENSG00000240534.1,0.365556,0.004545,0.018790,0.005840
1698,ENSG00000274818.1,0.174135,0.022727,0.008157,0.002794

In [31]:
filtered_df = result_dataframes_per_visit['V08'][(result_dataframes_per_visit['V08'].iloc[:, 1:] > 0).all(axis=1)]
filtered_df

,feature,importance_LR2,importance_SVM2,importance_RF2,importance_XGBOOST2
636,ENSG00000270962.1,0.058104,0.004762,0.001207,0.001397

In [33]:
result_dataframes_per_visit['BL']

,feature,importance_LR2,importance_SVM2,importance_RF2,importance_XGBOOST2
0,ENSG00000139668.8,0.000000,0.001187,0.000343,0.0
1,ENSG00000228860.1,0.193785,0.013892,0.000175,0.0
2,ENSG00000268777.1,0.000000,0.008404,0.000000,0.0
3,ENSG00000197265.8,0.000000,0.001016,0.000433,0.0
4,ENSG00000253282.1,0.000000,0.003579,0.000501,0.0
...,...,...,...,...,...
1880,ENSG00000156885.5,0.000000,0.002117,0.000020,0.0
1881,ENSG00000238658.1,0.000000,0.009188,0.000457,0.0
1882,ENSG00000270137.1,0.000000,0.004013,0.000091,0.0
1883,ENSG00000117899.10,-0.101837,0.008666,0.000201,0.0
1884,ENSG00000279507.1,0.000000,0.006182,0.000708,0.0

In [7]:
dataframes_per_visit = {}
for visit in visits:
    feature_importance_file = f"{PATH}/LR2/feature_importance_data_Male_50-70_{visit}.csv"
    df = pd.read_csv(feature_importance_file)
    dataframes_per_visit[visit] = df

In [13]:
# Find the union of the 'feature' column across all dataframes in dataframes_per_visit
common_features = set.union(*[set(df['feature']) for df in dataframes_per_visit.values()])

{'ENSG00000222795.1', 'ENSG00000254754.1', 'ENSG00000236110.1', 'ENSG00000260923.6', 'ENSG00000280368.1', 'ENSG00000180305.4', 'ENSG00000238113.6', 'ENSG00000121743.3', 'ENSG00000259601.2', 'ENSG00000259915.2', 'ENSG00000267356.1', 'ENSG00000273253.2', 'ENSG00000203943.8', 'ENSG00000116954.7', 'ENSG00000231366.1', 'ENSG00000274584.1', 'ENSG00000226566.2', 'ENSG00000279067.1', 'ENSG00000239272.1', 'ENSG00000213423.4', 'ENSG00000237892.1', 'ENSG00000253857.1', 'ENSG00000273891.1', 'ENSG00000261010.1', 'ENSG00000102683.7', 'ENSG00000169231.13', 'ENSG00000061492.11', 'ENSG00000280665.1', 'ENSG00000279725.1', 'ENSG00000255745.1', 'ENSG00000047249.17', 'ENSG00000228489.1', 'ENSG00000229863.1', 'ENSG00000242296.2', 'ENSG00000270755.1', 'ENSG00000215788.10', 'ENSG00000285730.1', 'ENSG00000134830.5', 'ENSG00000267593.1', 'ENSG00000254686.2', 'ENSG00000261752.1', 'ENSG00000255516.1', 'ENSG00000174015.9', 'ENSG00000253665.1', 'ENSG00000161328.10', 'ENSG00000233203.6', 'ENSG00000228794.8', 'ENSG00000259608.1', 'ENSG00000201943.1', 'ENSG00000276692.1', 'ENSG00000241131.1', 'ENSG00000235926.1', 'ENSG00000279507.1', 'ENSG00000261080.1', 'ENSG00000280382.1', 'ENSG00000164129.11', 'ENSG00000254902.1', 'ENSG00000229587.2', 'ENSG00000199475.1', 'ENSG00000237571.1', 'ENSG00000154429.10', 'ENSG00000227313.1', 'ENSG00000215301.10', 'ENSG00000238457.1', 'ENSG00000254205.1', 'ENSG00000185825.16', 'ENSG00000255170.2', 'ENSG00000184144.11', 'ENSG00000246740.2', 'ENSG00000253688.2', 'ENSG00000069248.11', 'ENSG00000265740.2', 'ENSG00000238098.9', 'ENSG00000225433.3', 'ENSG00000189132.6', 'ENSG00000154928.17', 'ENSG00000276527.1', 'ENSG00000244561.1', 'ENSG00000235781.1', 'ENSG00000234485.5', 'ENSG00000279137.1', 'ENSG00000133193.12', 'ENSG00000243415.2', 'ENSG00000241211.1', 'ENSG00000262112.1', 'ENSG00000261715.1', 'ENSG00000165671.20', 'ENSG00000234300.1', 'ENSG00000223488.2', 'ENSG00000167615.16', 'ENSG00000257956.1', 'ENSG00000151962.7', 'ENSG00000238837.3', 'ENSG00000237445.2', 'ENSG00000240045.1', 'ENSG00000130287.13', 'ENSG00000259522.3', 'ENSG00000234985.2', 'ENSG00000200857.1', 'ENSG00000205765.8', 'ENSG00000177669.3', 'ENSG00000156990.14', 'ENSG00000258913.1', 'ENSG00000182586.8', 'ENSG00000202233.2', 'ENSG00000259416.2', 'ENSG00000253571.1', 'ENSG00000263177.1', 'ENSG00000279570.1', 'ENSG00000275194.1', 'ENSG00000279914.1', 'ENSG00000225581.3', 'ENSG00000116406.18', 'ENSG00000207185.1', 'ENSG00000134644.15', 'ENSG00000181656.6', 'ENSG00000270115.1', 'ENSG00000220291.1', 'ENSG00000260173.1', 'ENSG00000248336.1', 'ENSG00000206635.1', 'ENSG00000225849.2', 'ENSG00000271230.1', 'ENSG00000122584.12', 'ENSG00000224459.1', 'ENSG00000248027.1', 'ENSG00000260213.6', 'ENSG00000224155.2', 'ENSG00000237349.1', 'ENSG00000224431.1', 'ENSG00000244501.3', 'ENSG00000250475.1', 'ENSG00000237321.1', 'ENSG00000167395.10', 'ENSG00000266987.1', 'ENSG00000132950.18', 'ENSG00000273068.1', 'ENSG00000280438.1', 'ENSG00000244236.3', 'ENSG00000243193.4', 'ENSG00000132622.10', 'ENSG00000199572.1', 'ENSG00000252639.1', 'ENSG00000201114.1', 'ENSG00000201831.1', 'ENSG00000213091.2', 'ENSG00000250667.1', 'ENSG00000111218.11', 'ENSG00000248548.1', 'ENSG00000263772.1', 'ENSG00000254930.1', 'ENSG00000105146.12', 'ENSG00000159720.11', 'ENSG00000228599.1', 'ENSG00000269560.1', 'ENSG00000221038.1', 'ENSG00000278408.1', 'ENSG00000242853.3', 'ENSG00000259969.1', 'ENSG00000222365.1', 'ENSG00000237221.1', 'ENSG00000235876.2', 'ENSG00000274841.1', 'ENSG00000175931.12', 'ENSG00000217330.1', 'ENSG00000221491.2', 'ENSG00000280414.1', 'ENSG00000236762.1', 'ENSG00000268879.1', 'ENSG00000187766.1', 'ENSG00000225427.1', 'ENSG00000101310.16', 'ENSG00000232526.1', 'ENSG00000187242.5', 'ENSG00000276759.2', 'ENSG00000285561.1', 'ENSG00000263505.1', 'ENSG00000183439.7', 'ENSG00000244441.1', 'ENSG00000118308.15', 'ENSG00000253261.1', 'ENSG00000105325.13', 'ENSG00000275953.1', 'ENSG00000230595.1', 'ENSG00000228611.2', 'ENSG00000237606.2', 'ENSG00000266545.1', 'ENSG00000236248.1', 'ENSG00000259615.1', 'ENSG00000169814.13', 'ENSG00000147100.10', 'ENSG00000258569.1', 'ENSG00000119844.15', 'ENSG00000248107.1', 'ENSG00000215486.5', 'ENSG00000048740.18', 'ENSG00000159579.13', 'ENSG00000239671.1', 'ENSG00000228658.1', 'ENSG00000248977.1', 'ENSG00000206043.6', 'ENSG00000228781.1', 'ENSG00000199970.1', 'ENSG00000280580.1', 'ENSG00000267333.1', 'ENSG00000261436.5', 'ENSG00000233603.1', 'ENSG00000104804.7', 'ENSG00000219150.2', 'ENSG00000213736.2', 'ENSG00000172366.19', 'ENSG00000227613.1', 'ENSG00000164010.14', 'ENSG00000285704.1', 'ENSG00000196646.11', 'ENSG00000270619.1', 'ENSG00000152591.13', 'ENSG00000271237.1', 'ENSG00000281548.1', 'ENSG00000253966.1', 'ENSG00000277981.1', 'ENSG00000152093.7', 'ENSG00000231777.1', 'ENSG00000170454.5', 'ENSG00000233372.1', 'ENSG00000167910.3', 'ENSG00000132026.13', 'ENSG00000266503.2', 'ENSG00000138772.12', 'ENSG00000267202.5', 'ENSG00000267501.1', 'ENSG00000160180.15', 'ENSG00000266236.1', 'ENSG00000236690.2', 'ENSG00000163202.4', 'ENSG00000224354.2', 'ENSG00000168267.6', 'ENSG00000236754.5', 'ENSG00000234753.5', 'ENSG00000227523.1', 'ENSG00000235435.1', 'ENSG00000205944.11', 'ENSG00000248122.1', 'ENSG00000280958.1', 'ENSG00000280283.1', 'ENSG00000225728.2', 'ENSG00000185946.15', 'ENSG00000137225.12', 'ENSG00000275767.1', 'ENSG00000227128.4', 'ENSG00000237517.9', 'ENSG00000221479.3', 'ENSG00000230471.1', 'ENSG00000196183.5', 'ENSG00000234256.2', 'ENSG00000253072.1', 'ENSG00000270627.1', 'ENSG00000221459.1', 'ENSG00000266756.1', 'ENSG00000114698.14', 'ENSG00000271108.1', 'ENSG00000261669.1', 'ENSG00000180919.3', 'ENSG00000224806.2', 'ENSG00000162727.3', 'ENSG00000135823.13', 'ENSG00000105989.9', 'ENSG00000266904.5', 'ENSG00000248557.1', 'ENSG00000180901.10', 'ENSG00000215274.5', 'ENSG00000165935.9', 'ENSG00000259183.1', 'ENSG00000250166.2', 'ENSG00000235126.1', 'ENSG00000141750.6', 'ENSG00000284932.1', 'ENSG00000250752.2', 'ENSG00000140474.13', 'ENSG00000108309.13', 'ENSG00000276348.1', 'ENSG00000132635.16', 'ENSG00000260443.1', 'ENSG00000116128.10', 'ENSG00000270282.1', 'ENSG00000236466.1', 'ENSG00000099715.14', 'ENSG00000204019.4', 'ENSG00000253759.1', 'ENSG00000249160.4', 'ENSG00000241203.1', 'ENSG00000267529.3', 'ENSG00000248409.2', 'ENSG00000226516.7', 'ENSG00000100101.15', 'ENSG00000185033.14', 'ENSG00000231032.1', 'ENSG00000181013.3', 'ENSG00000148090.11', 'ENSG00000234685.1', 'ENSG00000250772.5', 'ENSG00000226636.1', 'ENSG00000255258.2', 'ENSG00000254496.1', 'ENSG00000275649.1', 'ENSG00000230497.2', 'ENSG00000206812.1', 'ENSG00000252169.1', 'ENSG00000266995.1', 'ENSG00000165471.6', 'ENSG00000257129.1', 'ENSG00000239189.1', 'ENSG00000223587.1', 'ENSG00000201708.1', 'ENSG00000268186.1', 'ENSG00000099985.3', 'ENSG00000219088.1', 'ENSG00000171298.12', 'ENSG00000283162.1', 'ENSG00000261716.2', 'ENSG00000281825.1', 'ENSG00000234147.1', 'ENSG00000235824.4', 'ENSG00000269416.5', 'ENSG00000264643.1', 'ENSG00000205786.8', 'ENSG00000170961.6', 'ENSG00000136352.17', 'ENSG00000189372.4', 'ENSG00000105501.12', 'ENSG00000111046.3', 'ENSG00000222835.1', 'ENSG00000215156.5', 'ENSG00000266549.1', 'ENSG00000188895.11', 'ENSG00000278925.1', 'ENSG00000059145.18', 'ENSG00000241416.1', 'ENSG00000278044.1', 'ENSG00000259462.2', 'ENSG00000269931.1', 'ENSG00000010626.14', 'ENSG00000238124.1', 'ENSG00000142513.5', 'ENSG00000224322.1', 'ENSG00000260868.1', 'ENSG00000167701.13', 'ENSG00000267406.1', 'ENSG00000232989.1', 'ENSG00000261041.1', 'ENSG00000228800.1', 'ENSG00000241668.2', 'ENSG00000224001.2', 'ENSG00000230618.3', 'ENSG00000268335.1', 'ENSG00000256518.3', 'ENSG00000276107.1', 'ENSG00000234945.7', 'ENSG00000258420.1', 'ENSG00000243795.1', 'ENSG00000236343.1', 'ENSG00000269014.1', 'ENSG00000102763.17', 'ENSG00000250340.1', 'ENSG00000234607.2', 'ENSG00000260972.1', 'ENSG00000234961.1', 'ENSG00000179172.9', 'ENSG00000204779.2', 'ENSG00000253208.1', 'ENSG00000262974.1', 'ENSG00000177981.10', 'ENSG00000080007.7', 'ENSG00000281732.1', 'ENSG00000272900.1', 'ENSG00000186803.3', 'ENSG00000202206.1', 'ENSG00000233714.1', 'ENSG00000100601.9', 'ENSG00000065526.10', 'ENSG00000233606.2', 'ENSG00000232451.1', 'ENSG00000199471.1', 'ENSG00000253299.1', 'ENSG00000272359.1', 'ENSG00000227536.1', 'ENSG00000224602.1', 'ENSG00000272167.2', 'ENSG00000237055.1', 'ENSG00000014257.15', 'ENSG00000232284.7', 'ENSG00000221819.6', 'ENSG00000282299.1', 'ENSG00000178248.11', 'ENSG00000170836.11', 'ENSG00000283547.1', 'ENSG00000019995.6', 'ENSG00000266265.3', 'ENSG00000259042.2', 'ENSG00000224953.1', 'ENSG00000239560.3', 'ENSG00000250897.2', 'ENSG00000207204.1', 'ENSG00000179348.11', 'ENSG00000255408.3', 'ENSG00000278522.4', 'ENSG00000274653.1', 'ENSG00000238278.3', 'ENSG00000238097.1', 'ENSG00000279838.1', 'ENSG00000277203.1', 'ENSG00000091664.8', 'ENSG00000227766.1', 'ENSG00000166049.10', 'ENSG00000255490.1', 'ENSG00000155099.7', 'ENSG00000212340.1', 'ENSG00000201088.1', 'ENSG00000115592.11', 'ENSG00000243274.3', 'ENSG00000226101.1', 'ENSG00000226891.8', 'ENSG00000240235.3', 'ENSG00000243179.1', 'ENSG00000166189.7', 'ENSG00000253358.1', 'ENSG00000263717.1', 'ENSG00000265833.1', 'ENSG00000248328.1', 'ENSG00000235012.1', 'ENSG00000284629.1', 'ENSG00000235677.1', 'ENSG00000232520.1', 'ENSG00000233353.1', 'ENSG00000152592.13', 'ENSG00000129749.3', 'ENSG00000139797.7', 'ENSG00000137860.11', 'ENSG00000267769.1', 'ENSG00000248319.1', 'ENSG00000150175.13', 'ENSG00000271702.1', 'ENSG00000235641.4', 'ENSG00000249735.1', 'ENSG00000218536.1', 'ENSG00000232852.1', 'ENSG00000206705.1', 'ENSG00000199580.1', 'ENSG00000078725.12', 'ENSG00000155070.8', 'ENSG00000276702.1', 'ENSG00000266242.1', 'ENSG00000279542.1', 'ENSG00000179008.8', 'ENSG00000274594.1', 'ENSG00000267209.5', 'ENSG00000207158.1', 'ENSG00000252040.1', 'ENSG00000259532.1', 'ENSG00000271187.1', 'ENSG00000227443.2', 'ENSG00000259481.1', 'ENSG00000273461.5', 'ENSG00000134398.14', 'ENSG00000250467.1', 'ENSG00000218459.1', 'ENSG00000274492.1', 'ENSG00000231983.1', 'ENSG00000243746.1', 'ENSG00000224476.3', 'ENSG00000234122.1', 'ENSG00000285863.1', 'ENSG00000270861.1', 'ENSG00000274019.1', 'ENSG00000145147.19', 'ENSG00000213747.2', 'ENSG00000234795.9', 'ENSG00000169752.16', 'ENSG00000248431.1', 'ENSG00000242653.3', 'ENSG00000269907.1', 'ENSG00000275481.1', 'ENSG00000231929.2', 'ENSG00000231205.11', 'ENSG00000279716.1', 'ENSG00000108452.1', 'ENSG00000229434.1', 'ENSG00000196832.4', 'ENSG00000172421.9', 'ENSG00000122507.20', 'ENSG00000167815.11', 'ENSG00000274505.1', 'ENSG00000226535.1', 'ENSG00000162840.4', 'ENSG00000252329.1', 'ENSG00000260799.1', 'ENSG00000172912.4', 'ENSG00000102081.14', 'ENSG00000157214.13', 'ENSG00000224160.1', 'ENSG00000255853.1', 'ENSG00000250682.5', 'ENSG00000270683.1', 'ENSG00000271601.3', 'ENSG00000112769.18', 'ENSG00000112299.7', 'ENSG00000146938.15', 'ENSG00000234751.1', 'ENSG00000255409.1', 'ENSG00000103005.11', 'ENSG00000189181.4', 'ENSG00000232749.2', 'ENSG00000272597.1', 'ENSG00000237816.1', 'ENSG00000250812.2', 'ENSG00000228860.1', 'ENSG00000144579.7', 'ENSG00000273860.1', 'ENSG00000240760.1', 'ENSG00000261320.1', 'ENSG00000276486.1', 'ENSG00000221698.1', 'ENSG00000225706.1', 'ENSG00000266707.1', 'ENSG00000229360.1', 'ENSG00000272736.5', 'ENSG00000183035.12', 'ENSG00000236770.1', 'ENSG00000137634.9', 'ENSG00000228983.9', 'ENSG00000270422.1', 'ENSG00000229197.1', 'ENSG00000234736.5', 'ENSG00000076944.15', 'ENSG00000244559.1', 'ENSG00000272267.2', 'ENSG00000277387.1', 'ENSG00000241032.3', 'ENSG00000274929.1', 'ENSG00000259368.1', 'ENSG00000244405.7', 'ENSG00000254703.2', 'ENSG00000230944.1', 'ENSG00000167912.5', 'ENSG00000264897.1', 'ENSG00000110025.12', 'ENSG00000154589.6', 'ENSG00000242675.1', 'ENSG00000225893.1', 'ENSG00000187616.4', 'ENSG00000270372.1', 'ENSG00000226142.2', 'ENSG00000259645.1', 'ENSG00000200755.1', 'ENSG00000207483.1', 'ENSG00000237279.2', 'ENSG00000260399.1', 'ENSG00000230368.2', 'ENSG00000188290.10', 'ENSG00000138613.13', 'ENSG00000169550.13', 'ENSG00000251603.1', 'ENSG00000200340.1', 'ENSG00000227987.1', 'ENSG00000200318.2', 'ENSG00000158517.13', 'ENSG00000187175.5', 'ENSG00000165202.3', 'ENSG00000243910.7', 'ENSG00000257568.1', 'ENSG00000129170.9', 'ENSG00000237979.1', 'ENSG00000265179.6', 'ENSG00000179152.19', 'ENSG00000252336.1', 'ENSG00000282925.1', 'ENSG00000251878.1', 'ENSG00000267534.3', 'ENSG00000229203.1', 'ENSG00000207650.1', 'ENSG00000232730.1', 'ENSG00000239641.1', 'ENSG00000134874.17', 'ENSG00000198526.7', 'ENSG00000284701.1', 'ENSG00000265639.1', 'ENSG00000239893.1', 'ENSG00000276366.1', 'ENSG00000257268.1', 'ENSG00000092068.19', 'ENSG00000283307.1', 'ENSG00000274026.1', 'ENSG00000205444.3', 'ENSG00000219409.2', 'ENSG00000234112.2', 'ENSG00000243635.1', 'ENSG00000236900.1', 'ENSG00000248323.6', 'ENSG00000266965.1', 'ENSG00000248441.6', 'ENSG00000188662.6', 'ENSG00000198854.5', 'ENSG00000135525.18', 'ENSG00000266693.1', 'ENSG00000127083.7', 'ENSG00000225473.1', 'ENSG00000215263.2', 'ENSG00000218109.5', 'ENSG00000234247.1', 'ENSG00000257173.1', 'ENSG00000179915.22', 'ENSG00000269067.1', 'ENSG00000162365.11', 'ENSG00000260348.1', 'ENSG00000252955.1', 'ENSG00000254433.1', 'ENSG00000237447.1', 'ENSG00000250561.2', 'ENSG00000057704.12', 'ENSG00000266017.1', 'ENSG00000230275.2', 'ENSG00000201916.1', 'ENSG00000206600.1', 'ENSG00000273136.6', 'ENSG00000207173.1', 'ENSG00000270672.1', 'ENSG00000245248.7', 'ENSG00000276521.1', 'ENSG00000240950.1', 'ENSG00000254855.1', 'ENSG00000201711.1', 'ENSG00000158850.14', 'ENSG00000276577.1', 'ENSG00000226205.1', 'ENSG00000278952.1', 'ENSG00000214976.2', 'ENSG00000261873.2', 'ENSG00000213420.7', 'ENSG00000244471.6', 'ENSG00000254993.2', 'ENSG00000278724.1', 'ENSG00000143367.15', 'ENSG00000274493.1', 'ENSG00000251410.1', 'ENSG00000141428.16', 'ENSG00000223597.2', 'ENSG00000152910.18', 'ENSG00000171360.3', 'ENSG00000277058.2', 'ENSG00000225925.1', 'ENSG00000202190.1', 'ENSG00000261687.1', 'ENSG00000228506.1', 'ENSG00000101363.12', 'ENSG00000254811.5', 'ENSG00000108953.16', 'ENSG00000251478.1', 'ENSG00000255374.3', 'ENSG00000198797.6', 'ENSG00000282034.1', 'ENSG00000256690.1', 'ENSG00000267557.1', 'ENSG00000187747.2', 'ENSG00000225238.1', 'ENSG00000199506.1', 'ENSG00000259779.1', 'ENSG00000271624.1', 'ENSG00000254312.1', 'ENSG00000252362.1', 'ENSG00000249833.5', 'ENSG00000238212.2', 'ENSG00000230589.1', 'ENSG00000258027.2', 'ENSG00000271340.1', 'ENSG00000258662.1', 'ENSG00000248659.1', 'ENSG00000248645.1', 'ENSG00000270776.1', 'ENSG00000266560.5', 'ENSG00000223076.1', 'ENSG00000285618.1', 'ENSG00000164920.9', 'ENSG00000174177.12', 'ENSG00000271437.1', 'ENSG00000173253.15', 'ENSG00000253300.1', 'ENSG00000116194.12', 'ENSG00000261807.2', 'ENSG00000243584.1', 'ENSG00000264963.2', 'ENSG00000147127.8', 'ENSG00000255335.1', 'ENSG00000261729.1', 'ENSG00000251281.1', 'ENSG00000237107.3', 'ENSG00000250972.1', 'ENSG00000248958.2', 'ENSG00000198099.8', 'ENSG00000248307.5', 'ENSG00000145740.18', 'ENSG00000237758.1', 'ENSG00000147202.17', 'ENSG00000254112.1', 'ENSG00000171587.14', 'ENSG00000257021.1', 'ENSG00000250183.2', 'ENSG00000259192.1', 'ENSG00000267455.1', 'ENSG00000279202.1', 'ENSG00000248550.3', 'ENSG00000234698.1', 'ENSG00000252289.1', 'ENSG00000199468.1', 'ENSG00000199177.1', 'ENSG00000197565.15', 'ENSG00000165490.12', 'ENSG00000237338.1', 'ENSG00000258935.1', 'ENSG00000174943.10', 'ENSG00000133059.16', 'ENSG00000221325.1', 'ENSG00000168137.15', 'ENSG00000178394.4', 'ENSG00000162891.10', 'ENSG00000215398.11', 'ENSG00000140521.13', 'ENSG00000213049.3', 'ENSG00000212428.1', 'ENSG00000200822.1', 'ENSG00000182613.2', 'ENSG00000253702.1', 'ENSG00000105722.9', 'ENSG00000259468.1', 'ENSG00000171016.12', 'ENSG00000169953.11', 'ENSG00000235698.1', 'ENSG00000236939.2', 'ENSG00000257823.1', 'ENSG00000234036.4', 'ENSG00000070778.12', 'ENSG00000213882.2', 'ENSG00000252945.1', 'ENSG00000229897.2', 'ENSG00000149090.11', 'ENSG00000234593.2', 'ENSG00000172932.14', 'ENSG00000255215.1', 'ENSG00000261116.1', 'ENSG00000242019.1', 'ENSG00000273796.1', 'ENSG00000259719.5', 'ENSG00000234324.1', 'ENSG00000171864.4', 'ENSG00000112246.9', 'ENSG00000233017.2', 'ENSG00000229409.1', 'ENSG00000252580.1', 'ENSG00000221840.4', 'ENSG00000199301.1', 'ENSG00000163888.3', 'ENSG00000255958.1', 'ENSG00000283469.1', 'ENSG00000188906.15', 'ENSG00000224869.1', 'ENSG00000249831.2', 'ENSG00000280097.1', 'ENSG00000276054.1', 'ENSG00000274985.1', 'ENSG00000186825.5', 'ENSG00000283849.1', 'ENSG00000233632.1', 'ENSG00000265195.1', 'ENSG00000173093.12', 'ENSG00000255082.1', 'ENSG00000173124.14', 'ENSG00000223922.1', 'ENSG00000261818.1', 'ENSG00000207761.3', 'ENSG00000198674.3', 'ENSG00000132256.18', 'ENSG00000259944.1', 'ENSG00000271386.1', 'ENSG00000284095.1', 'ENSG00000180044.5', 'ENSG00000189410.11', 'ENSG00000168418.7', 'ENSG00000277223.1', 'ENSG00000268541.1', 'ENSG00000261629.1', 'ENSG00000231620.1', 'ENSG00000250406.1', 'ENSG00000261460.1', 'ENSG00000249482.1', 'ENSG00000241679.2', 'ENSG00000185221.6', 'ENSG00000181350.11', 'ENSG00000229735.1', 'ENSG00000226663.2', 'ENSG00000260454.1', 'ENSG00000278124.1', 'ENSG00000235571.1', 'ENSG00000249206.2', 'ENSG00000233782.1', 'ENSG00000164754.14', 'ENSG00000135968.20', 'ENSG00000226693.1', 'ENSG00000227238.1', 'ENSG00000214835.3', 'ENSG00000259362.2', 'ENSG00000139364.10', 'ENSG00000248771.5', 'ENSG00000215034.4', 'ENSG00000244706.2', 'ENSG00000230778.1', 'ENSG00000275103.1', 'ENSG00000261296.1', 'ENSG00000235403.1', 'ENSG00000070540.12', 'ENSG00000163694.14', 'ENSG00000201036.1', 'ENSG00000249706.1', 'ENSG00000272480.1', 'ENSG00000241457.1', 'ENSG00000219387.2', 'ENSG00000273746.1', 'ENSG00000263800.1', 'ENSG00000251189.1', 'ENSG00000234172.1', 'ENSG00000204140.9', 'ENSG00000261578.1', 'ENSG00000225212.4', 'ENSG00000240494.2', 'ENSG00000200398.1', 'ENSG00000259082.1', 'ENSG00000266765.1', 'ENSG00000235945.1', 'ENSG00000103994.17', 'ENSG00000197826.11', 'ENSG00000277988.1', 'ENSG00000269833.2', 'ENSG00000228196.1', 'ENSG00000175782.9', 'ENSG00000252746.1', 'ENSG00000223342.2', 'ENSG00000271358.1', 'ENSG00000101443.17', 'ENSG00000249392.1', 'ENSG00000165805.9', 'ENSG00000243945.1', 'ENSG00000137414.5', 'ENSG00000166927.12', 'ENSG00000225603.3', 'ENSG00000284711.1', 'ENSG00000223843.4', 'ENSG00000274044.4', 'ENSG00000222607.1', 'ENSG00000280424.1', 'ENSG00000259107.1', 'ENSG00000225129.1', 'ENSG00000263573.1', 'ENSG00000255494.1', 'ENSG00000251998.1', 'ENSG00000171711.2', 'ENSG00000138668.18', 'ENSG00000273167.1', 'ENSG00000251471.1', 'ENSG00000200872.1', 'ENSG00000277418.1', 'ENSG00000271286.1', 'ENSG00000070985.13', 'ENSG00000172478.17', 'ENSG00000250622.1', 'ENSG00000229492.1', 'ENSG00000274469.1', 'ENSG00000265635.1', 'ENSG00000277146.1', 'ENSG00000169551.12', 'ENSG00000181296.3', 'ENSG00000252321.1', 'ENSG00000214904.5', 'ENSG00000281664.1', 'ENSG00000279724.1', 'ENSG00000224584.2', 'ENSG00000118777.11', 'ENSG00000004838.13', 'ENSG00000221265.1', 'ENSG00000236842.1', 'ENSG00000248311.1', 'ENSG00000273759.1', 'ENSG00000176125.4', 'ENSG00000255276.1', 'ENSG00000200718.1', 'ENSG00000238658.1', 'ENSG00000233858.4', 'ENSG00000225174.1', 'ENSG00000272138.1', 'ENSG00000272337.1', 'ENSG00000162761.14', 'ENSG00000253725.1', 'ENSG00000253417.5', 'ENSG00000172935.8', 'ENSG00000254572.2', 'ENSG00000207296.1', 'ENSG00000222068.1', 'ENSG00000275878.1', 'ENSG00000263237.1', 'ENSG00000280446.1', 'ENSG00000153956.15', 'ENSG00000112541.14', 'ENSG00000214604.3', 'ENSG00000260026.1', 'ENSG00000252759.1', 'ENSG00000142698.14', 'ENSG00000242790.1', 'ENSG00000134058.11', 'ENSG00000280350.1', 'ENSG00000285462.1', 'ENSG00000165973.18', 'ENSG00000233693.1', 'ENSG00000259564.2', 'ENSG00000252307.1', 'ENSG00000234854.1', 'ENSG00000112276.13', 'ENSG00000276213.1', 'ENSG00000234315.1', 'ENSG00000252719.1', 'ENSG00000187657.6', 'ENSG00000177993.3', 'ENSG00000168539.3', 'ENSG00000257392.1', 'ENSG00000043039.6', 'ENSG00000249493.1', 'ENSG00000161265.14', 'ENSG00000135903.19', 'ENSG00000163453.11', 'ENSG00000227514.3', 'ENSG00000254593.1', 'ENSG00000227982.1', 'ENSG00000136044.11', 'ENSG00000132464.11', 'ENSG00000230031.10', 'ENSG00000165632.7', 'ENSG00000273125.1', 'ENSG00000225870.1', 'ENSG0000023414

In [14]:
len(common_features)

9469